# Generated by Django 3.2.12 on 2022-04-20 20:38

from django.db import migrations, models
import django.db.models.deletion
import picture.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=20, verbose_name='图片标题')),
                ('introduction', models.TextField(default='no introduction', max_length=300, verbose_name='图片介绍')),
                ('likesNum', models.IntegerField(default=0, verbose_name='图片的点赞')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pic', models.ImageField(default='pictures/default.png', storage=picture.storage.ImageStorage(),
                                          upload_to='pictures', verbose_name='图片文件')),
                ('public', models.IntegerField(default=0, verbose_name='图片是否公开')),
                ('collectionNum', models.IntegerField(default=0, verbose_name='收藏数')),
                ('repair_already', models.IntegerField(default=0, verbose_name='已完成的修复步骤数')),
                ('repair_times', models.IntegerField(default=0, verbose_name='修复操作数目')),
                ('collection_users',
                 models.ManyToManyField(blank=True, related_name='picture_collection', to='user.User',
                                        verbose_name='收藏的用户')),
                ('img', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='picture.image',
                                             verbose_name='图片的二进制存储')),
                ('like_users',
                 models.ManyToManyField(blank=True, related_name='picture_like', to='user.User', verbose_name='点赞的用户')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='标签')),
            ],
        ),
        migrations.CreateModel(
            name='Repair_step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=0, verbose_name='修复的步骤')),
                ('api', models.CharField(max_length=50, verbose_name='调用的接口')),
                ('pic', models.ImageField(default='repair/default.png', storage=picture.storage.ImageStorage(),
                                          upload_to='repair', verbose_name='修复后的图片')),
                ('img', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='picture.image',
                                             verbose_name='图片的二进制存储')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture.picture',
                                              verbose_name='修复的图片')),
            ],
        ),
        migrations.CreateModel(
            name='Picture_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
                ('picture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='picture.picture',
                                                 verbose_name='浏览的展览')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user',
                                              verbose_name='浏览的用户')),
            ],
        ),
        migrations.CreateModel(
            name='Picture_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=400, verbose_name='评论内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发表的时间')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture.picture',
                                              verbose_name='评论的图片')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='发表的用户')),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='tags',
            field=models.ManyToManyField(blank=True, to='picture.Tag', verbose_name='标签列表'),
        ),
    ]
