# Generated by Django 3.2.12 on 2022-04-20 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture_history',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture.picture',
                                    verbose_name='浏览的展览'),
        ),
        migrations.AlterField(
            model_name='picture_history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='浏览的用户'),
        ),
    ]
