# Generated by Django 3.2.12 on 2022-04-20 20:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import picture.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='登录时间')),
                ('avatar',
                 models.ImageField(default='user/default.png', storage=picture.storage.ImageStorage(), upload_to='user',
                                   verbose_name='用户头像')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='用户邮箱')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='root权限')),
                ('is_admin', models.BooleanField(default=False, verbose_name='管理员权限')),
                ('is_register', models.BooleanField(default=True, verbose_name='待注册用户')),
                ('is_active', models.BooleanField(default=True, verbose_name='用户是否活跃')),
                ('freeze', models.BooleanField(default=False, verbose_name='是否永久封禁')),
                ('free_date', models.DateTimeField(blank=True, default=datetime.datetime(2001, 9, 9, 9, 46, 40),
                                                   verbose_name='解封日期')),
                ('img',
                 models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.avatar_image',
                                      verbose_name='图片的二进制存储')),
            ],
        ),
    ]
