# Generated by Django 3.2.12 on 2022-04-26 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avatar_Image',
            new_name='AvatarImage',
        ),
    ]
