# Generated by Django 3.2.12 on 2022-04-20 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('picture', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=20, verbose_name='展览标题')),
                ('introduction', models.TextField(default='no introduction', max_length=300, verbose_name='展览介绍')),
                ('likesNum', models.IntegerField(default=0, verbose_name='点赞数')),
                ('style', models.IntegerField(default=0, verbose_name='样式')),
                ('public', models.IntegerField(default=0, verbose_name='是否公开')),
                ('collectionNum', models.IntegerField(default=0, verbose_name='收藏数')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('collection_users',
                 models.ManyToManyField(blank=True, related_name='exhibit_collection', to='user.User',
                                        verbose_name='收藏的用户')),
                ('like_users', models.ManyToManyField(blank=True, related_name='exhibit_like', to='user.User',
                                                      verbose_name='点过赞的用户')),
                ('pictures', models.ManyToManyField(blank=True, to='picture.Picture', verbose_name='图片列表')),
                ('tags', models.ManyToManyField(blank=True, to='picture.Tag', verbose_name='标签列表')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
                ('exhibit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exhibit.exhibit',
                                                 verbose_name='浏览的展览')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user',
                                              verbose_name='浏览的用户')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=400, verbose_name='内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibit.exhibit',
                                              verbose_name='评论的展览')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='发表的用户')),
            ],
        ),
    ]
