# Generated by Django 3.2.12 on 2022-04-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_rename_avatar_image_avatarimage'),
        ('exhibit', '0002_auto_20220420_2039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exhibit_comment',
            new_name='ExhibitComment',
        ),
        migrations.RenameModel(
            old_name='Exhibit_History',
            new_name='ExhibitHistory',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='modify_lock',
            field=models.IntegerField(default=0, verbose_name='信息修改是否在进行'),
        ),
    ]
